"use strict";
(function () {
    'use strict';
    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
    angular
        .module('smartcloudserviceApp')
        .constant('APP_NAME', '#project.name#')
        .constant('VERSION', '#project.version#')
        .constant('PAGINATION_CONSTANTS', {
            'itemsPerPage': 10
         })
//        .constant('ENV', '#mvn.profiles.active#')
        .constant('DEBUG_INFO_ENABLED', true);
})();